version: '3.8'

services:
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
  app:
    image: farm-app
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./frontend/:/usr/src/app
    ports:
      - 3000:3000
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080/api

  api:
    image: farm-api
    build:
      context: ./backend
      dockerfile: dev.DockerFile
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 3001:3001
    environment:
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    ports:
      - 27017:27017
    volumes:
      - ./mongo_seed:/docker-entrypoint-initdb.d
      - ./mongo_data:/data/db
    command: --quiet

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
