version: '3.8'

services:
  test:
    image: farm-test
    build:
      context: ./backend
      dockerfile: test.Dockerfile
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - TEST_MONGO_URL=mongodb://the_username:the_password@mongo-test:27017/the_test_database
    depends_on:
      - mongo-test

  mongo-test:
    image: mongo
    logging:
      driver: none
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_test_database
    volumes:
      - ./mongo_test_seed:/docker-entrypoint-initdb.d
      - ./mongo_test_data:/data/db
